### ISSUE TITLE
Image build not working: Nothing RPROVIDES 'flutter-pi

### ISSUE THREAD

**Issue by gerkol** [jwinarske/manifests#1]
Hi, I'm currently trying to build yocto linux for my raspberry pi 3B+ including the flutter-pi embedder. I'm following these steps:

```
mkdir rpi_64_yocto && cd rpi_64_yocto
repo init -u https://github.com/jwinarske/manifests.git -m rpi64.xml -b dunfell
repo sync -j20
source ./setup-environment $MACHINE
echo -e 'CORE_IMAGE_EXTRA_INSTALL += " \' >> conf/local.conf
echo -e '  flutter-pi \' >> conf/local.conf
echo -e '  flutter-drm-gbm-backend \' >> conf/local.conf
echo -e '"\n' >> conf/local.conf
bitbake core-image-minimal
```

However, I get an error saying ERROR: `Nothing PROVIDES 'flutter-pi'`

Also when syncing the repo, currently the `refs/heads/jw/dunfell-clang12` is not found. I think the **jw** has to be removed.

**Comment by jwinarske** [comment]
Take a look at these
```
https://github.com/meta-flutter/meta-flutter/blob/honister/.github/workflows/honister-rpi3-64.yml
https://github.com/meta-flutter/meta-flutter/blob/honister/.github/workflows/honister-rpi3-32.yml
```
Images and other packages are available to download via the Action jobs.

**Comment by gerkol** [comment]
Perfect thank you! 

I used the latest artifact from this pipeline: `https://github.com/meta-flutter/meta-flutter/blob/honister/.github/workflows/honister-rpi3-64.yml`.

However, for some reason, I cannot run my flutter app. I created an `app.so`. But now flutter-pi is still complaining: 

```
Could not find "libapp.so" file inside "flutter_assets/", which is required for release and profile mode.
```

**Comment by jwinarske** [comment]
@gerkol 
meta-flutter applies this patch to flutter-pi.  Note the AOT name:
https://github.com/meta-flutter/meta-flutter/blob/dunfell/recipes-graphics/flutter-pi/files/0001-path-updates.patch

All the embedders in meta-flutter with path variation have been adjusted.

**Comment by gerkol** [comment]
@jwinarske ah okay thank you. :) I just created the libapp.so using `flutter build apk --release`. But now I get the next error. And I cannot really find a useful answer ...

```
Error while initializing the Dart VM: Wrong full snapshot version, expected 'ded6ef11c73fdc638d6ff6d3ad22a67b' found 'd56742caf7b3b3f4bd2df93a9bbb5503'
Aborted
```

I guess it might be some version problem. I build my app using the latest flutter and dart version. Do you have any ideas?

**Comment by jwinarske** [comment]
@gerkol The Flutter SDK Dart VM used to generate the AOT needs to match the Dart VM used in the engine.  They cannot be mis-matched, or you will see that error.

**Comment by gerkol** [comment]
@gerkol Makes sense. I have a new error now: 

```
error while initializing the Dart VM: Snapshot not compatible with the current VM configuration:

the snapshot requires

 'product no-code_comments no-dwarf_stack_traces_mode lazy_async_stacks no-lazy_dispatchers dedup_instructions no-asserts arm64-sysv compressed-pointers null-safety'

but the VM has

 'product no-code_comments no-dwarf_stack_traces_mode lazy_async_stacks no-lazy_dispatchers dedup_instructions no-asserts arm64-sysv no-compressed-pointers null-safety'
```
So `no-compressed-pointers` is supposed to be `compressed-pointers`. Do you have an idea how to configure that?

**Comment by jwinarske** [comment]
@gerkol 
You need to build AOT with the engine SDK.  The meta-flutter flutter app bbclass contains the proper usage.

**Comment by gerkol** [comment]
@jwinarske okay i managed to build something that executes at least. However, I'm not sure where I can find ```${STAGING_DATADIR}/flutter/engine_sdk.zip```. I used https://github.com/ardera/flutter-engine-binaries-for-arm/blob/main/arm64/gen_snapshot_linux_x64_release instead. 

But I'm still getting errors: 

```
Shader compilation error
------------------------
   1	uniform half3 u_0_edgeArray_S1[4];in half4 vcolor_S0;half4 ConvexPoly_S1(half4 _input) {
   2	half _1_alpha = 1.0;half _2_edge;(_2_edge = dot(u_0_edgeArray_S1[0], half3(float3(sk_FragCoord.xy, 1.0))));(_2_edge = half(((_2_edge >= 0.5) ? 1.0 : 0.0)));(_1_alpha *= _2_edge);(_2_edge = dot(u_0_edgeArray_S1[1], half3(float3(sk_FragCoord.xy, 1.0))));(_2_edge = half(((_2_edge >= 0.5) ? 1.0 : 0.0)));(_1_alpha *= _2_edge);(_2_edge = dot(u_0_edgeArray_S1[2], half3(float3(sk_FragCoord.xy, 1.0))));(_2_edge = half(((_2_edge >= 0.5) ? 1.0 : 0.0)));(_1_alpha *= _2_edge);(_2_edge = dot(u_0_edgeArray_S1[3], half3(float3(sk_FragCoord.xy, 1.0))));(_2_edge = half(((_2_edge >= 0.5) ? 1.0 : 0.0)));(_1_alpha *= _2_edge);return (_input * _1_alpha);}
   3	
   4	void main() {// Stage 0, QuadPerEdgeAAGeometryProcessor
   5	half4 outputColor_S0;outputColor_S0 = vcolor_S0;const half4 outputCoverage_S0 = half4(1);half4 output_S1;output_S1 = ConvexPoly_S1(outputCoverage_S0);{ // Xfer Processor: Porter Duff Shader
   6	sk_FragColor = blend_src(outputColor_S0, _dstColor);sk_FragColor = output_S1 * sk_FragColor + (half4(1.0) - output_S1) * _dstColor;}}
Errors:
error: 6: unknown identifier '_dstColor'
error: 6: unknown identifier '_dstColor'
2 errors
```
